modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="danerick"
version="1.0.0"
displayName="Danerick's Mod"
authors="Henrique"
description='''Aoba'''

[[dependencies.danerick]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.danerick]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"